### ISSUE TITLE
Add .indexes command

### ISSUE THREAD

**Issue by yaziine** [genjidb/genji#100]
List all indexes:
```
genji> .indexes
```

List indexes of a specific table:
```
genji> .indexes user
```

**Comment by tzzed** [comment]
The behaviour of `.indexes` command should only list indexes name or returns table index information.
What kind of output is expected? Output json document or [Sql](https://dev.mysql.com/doc/refman/8.0/en/show-index.html)?

**Comment by asdine** [comment]
Good question @tzzed, I think it should be the same as with the `.tables` command: Just a list of names, one per line

**Comment by yaziine** [comment]
I think adding the name of the table and the field whose the index is configured to may worth it. 
```
genji> .indexes
idx_bar on user(name)
idx_foo on user(email)
```
where `user` is the table and `name` and `email` fields of that table.

**Comment by asdine** [comment]
I love this idea, let's do it ❤️

**Comment by tzzed** [comment]
What about the refactor of `Index struct`. Your suggestion leaves this issue out of context about the refactor.
So should I do an issue even to suggest the why?
