### ISSUE TITLE
Ignore input with whitespace only

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#106]
Whenever we press return with no input or whitespace only input in the CLI, it invites the user to add a `;`.
We should simply ignore the input.

Current behavior:

```
genji> <press return, with or without whitespace>
... <press ';', then return>
genji>
```

Expected behavior:

```
genji> <press return, with or without whitespace>
genji>
```

**Comment by yaziine** [comment]
If we run a query with whitespace after the `;`, it also invites to add a `;`.
```
genji> create table foo; <press return with whitespace after the ; >
... <press ';', then return>
genji>
```
