### ISSUE TITLE
UPDATE ... SET updates the wrong array indexes

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#107]
when we add a field into a document which contains an array with multiple indexes,  the field is added but the first index is replaced by the next.

`
INSERT INTO users (a) VALUES ([1, 0, 0]), ([2, 0]);
UPDATE users set min = 0;
select * from users;
{  "a": [ 1, 0, 0]}
{"a": [ 2, 0]}
`
The result is this:
`
{  "a": [ 2, 0], "min":  0}
{  "a": [ 2, 0], "min":  0}`

We can see the first index replaced by the next.

instead of 
`
{  "a": [ 1, 0, 0], "min":  0}
{"a": [ 2, 0], "min":  0}
`

I probably do the correction with the issue #92

**Comment by yaziine** [comment]
> I probably do the correction with the issue #92 

I suggest that in #92 you focus only on fixing the related issue and you do a separate PR for this one. 
What do you think?
