### ISSUE TITLE
UPDATE SET Allow double quote for field name

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#108]
`UPDATE table SET` must allow field name with double quotes 

`UPDATE friends SET "favorite game" = " splinter cell";`

Double quotes are not allowed, receiving an error:
**found favorite game, expected identifier at line 1, char 17**

**Comment by yaziine** [comment]
You need to use backquotes in this context cf: https://genji.dev/docs/genji-sql/lexical-structure/#identifiers

```
genji> UPDATE friends set `favorite game` = "splinter cell";
genji>
```

**Comment by asdine** [comment]
Closing this, as @yaziine answered.
Feel free to reopen if needed
