### ISSUE TITLE
Redis as storage engine

### ISSUE THREAD

**Issue by rock59** [genjidb/genji#116]
Hi
Is it possible to support Redis as storage engine ?

**Comment by asdine** [comment]
Genji is primarily designed for working with local embedded kv stores, so currently I have no idea how it would perform with a remote storage engine like Redis.
I think this could be an interesting experiment, especially if it's designed to solve one specific use case (mostly writes? with local caching? how should the cache be invalidated? Too many questions)
But I think some queries would perform very poorly (how do we handle a simple `SELECT * FROM foo`?).
I'm open to suggestions though

**Comment by asdine** [comment]
Closing this as this is not planned for the moment, experimentations are welcome though
