### ISSUE TITLE
Msgpack errors for all requests that call GetByField

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#136]
When doing a request we got a `msgpack` error.
Getting errors for the next Identifiers:

```
genji> SELECT * FROM users;
msgpack: invalid code=16 decoding map length
genji>update client set name = "foo";
msgpack: invalid code=22 decoding map length
genji> CREATE INDEX `main skill index` ON users(skills.0);
msgpack: invalid code=16 decoding map length
genji> DELETE FROM client where name = "foo";
msgpack: invalid code=22 decoding map length
```

Works for `CREATE TABLE`:
```
genji> CREATE TABLE bar;
```

 `dec.dec.DecodeMapLen()`  returns error, it seems it doesn't have a map code  see `_mapLen`.

**Comment by asdine** [comment]
@tzzed You are probably using an old database file. The introduction of messagepack is not backward compatible and doesn't work with database files created before this feature. You need to create a new one

**Comment by tzzed** [comment]
You are right!

**Comment by asdine** [comment]
Closing this, don't hesitate to reopen if needed
