### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by gedw99** [genjidb/genji#162]
Wondering what the design story is for migrations.

So when the DB is at v1 on the client, and then you change some code relating to the DB and redeploy the app to v2, you want at runtime on the client to detect the db is at V1 and run some Database migration code.

A quick search brings up this for example: https://github.com/pressly/goose

**Comment by asdine** [comment]
Our goal is to have Genji be compatible with migrations tools like these

**Comment by gedw99** [comment]
Ok thanks..  Will close for now, as this is clearly not a bug at all, but more just a future thing anyone can do.

**Comment by asdine** [comment]
Thank you @gedw99, if you have any question you can join the [Genji Slack chan](https://gophers.slack.com/messages/CKPCYQFE0) on Gophers Slack
