### ISSUE TITLE
Add .dump command

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#181]
The `.dump` command displays the database content as SQL queries. By default, it outputs all the database but it can also display only one table.

Let's say we have a database with multiple tables and indexes, here is a commented example of the expected output

```sql
genji> .dump
-- the dumped script must always be wrapped in a transaction
BEGIN TRANSACTION;
-- each table must be outputted one by one, with table creation first
-- then index creation
-- then inserts
CREATE TABLE foo;
CREATE INDEX idx_foo_a ON foo(a);
-- inserts should use the document notation, as it should be simpler to just encode the document to json and paste it after each VALUES clause
INSERT INTO foo VALUES {"a": 1};
-- DOUBLES must be outputted with a decimal point
INSERT INTO foo VALUES {"a": 2.0, "c": 3.1};
-- ...
-- blank line between tables

CREATE TABLE bar(
  a INTEGER PRIMARY KEY,
  b.c[0] DOUBLE BOT NULL
);
-- ...
COMMIT;
```

**Comment by tzzed** [comment]
Is the `.dump` can take `table_name` as options?

**Comment by asdine** [comment]
Yes, it can

**Comment by tzzed** [comment]
The insert should print only the first document of the table or all documents?

**Comment by asdine** [comment]
It should dump everything, all documents. A "dump" is used to "export" the whole content

**Comment by tzzed** [comment]
Let me push the last change before?
