### ISSUE TITLE
Add the version command to the CLI

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#184]
```bash
$ genji version
Genji v0.7.1
Genji CLI v0.7.1
```

This requires storing the Genji and Genji CLI version in a variable and building it the CLI using build flags.

```go
// somewhere in CLI code
const Version = "development"

// somewhere in Genji code
const Version = "development" 
```

On CI, whenever a tag is created, use build flags to override the relevant variable with the version information from the tag.

**Comment by cvhariharan** [comment]
Hi, is this issue still open?
