### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by Indribell** [genjidb/genji#190]
Here is some fun of bad handled errors:

```go
	       ng, err := badgerengine.NewEngine(badger.DefaultOptions("mydb"))
		if err != nil {
			log.Fatal(err)
		}
		// Pass it to genji
		db, err := genji.New(ng)
		if err != nil {
			log.Fatal(err)
		}
		// Don't forget to close the database when you're done
		defer db.Close()

		// Create a table. Genji tables are schemaless, you don't need to specify a schema if not needed.
		err = db.Exec("CREATE TABLE user")
		if err != nil {
			log.Fatal(err)
		}

		// Create an index.
		err = db.Exec("CREATE INDEX idx_user_name ON test (name)")
		if err != nil {
			log.Fatal(err)
		}

		// Insert some data
		err = db.Exec("INSERT INTO user (id, name, age) VALUES (?, ?, ?)", 10, "Foo1", 15)
		if err != nil {
			log.Fatal(err)
		}

		// Or even to use structures
		type User struct {
			ID              uint
			Name            string
			TheAgeOfTheUser float64 `genji:"age"`
			Address         struct {
				City    string
				ZipCode string
			}
		}

		// Let's create a user
		u := User{
			ID:              20,
			Name:            "foo",
			TheAgeOfTheUser: 45,
		}
		u.Address.City = "Lyon"
		u.Address.ZipCode = "69001"

		err = db.Exec(`INSERT INTO user VALUES ?`, &u)

		// Query some documents
		res, err := db.Query("SELECT id, name, age, address FROM user") // WHERE age > ?", 18)
		if err != nil {
			log.Fatal(err)
		}
		defer res.Close()

		// always close the result when you're done with it
		// Iterate over the results
		err = res.Iterate(func(d document.Document) error {
			var id int
			var name string
			var age int32
			var address struct {
				City    string
				ZipCode string
			}

			err = document.Scan(d, &id, &name, &age, &address)
			if err != nil {
				return err
			}

			log.Println(id, name, age, address)
			return nil
		})
		if err != nil {
			log.Fatal(err)
		}

```

If you try out genji and play around a bit with the example.

I like to point attention to this line:

```go
res, err := db.Query("SELECT id, name, age, address FROM user") // WHERE age > ?", 18)
```
When data has been inserted before with "id, name, age" and you try to select on " id, name, age, address", your result is:

> 2020/09/14 01:09:42 cannot cast null as document

Yet, if you alter the code to:

```go
res, err := db.Query("SELECT id, name, age FROM user") // WHERE age > ?", 18)
```
You get all the results, including the 45 age user.

First the error code is ... non-descriptive. Yes, res is empty when using "address" but there is no real feedback to this point beyond a empty document warning.

Yes, i spend 30 minutes scratching my head as to why the example code did not work.

Then there is the issue that the code works, when you remove the address. So data got inserted from the struct but the address was not. Or it is? I can not tell by trying to fetch the data because even trying to select the document with a age > 18 ( aka the address user ) still result in a "cannot cast null as document" error.

This is inconstant behavior and feels just buggy as you can not trust the results.

**2.**

Other issue:

Now, if you want more fun, rerun the code with the database existing and watch the 

```go
err = db.Exec("CREATE TABLE user")
```

> 2020/09/14 01:28:22 table already exists

What table already exists?

**3.** 

```go
err = db.Exec("CREATE INDEX idx_user_name ON test (name)")
```

> 2020/09/14 01:29:49 table not found

Non-descriptive error.  Yes "test" does not exist ( please fix the example to use a correct user table )

Yes, those error issues can be solved with custom error handling but a bit more default error indicators is useful.

**4.**

```go
type User struct {
    ID              uint
    Name            []byte
    TheAgeOfTheUser float64 `genji:"age"`
    Address         struct {
        City    string
        ZipCode string
    }
}
```

This code is invalid as **Name** is a slice of byte but your trying to put a string into it only a few lines lower. The examples are a mix of code that is just ... not friendly and feel like a bunch of concept copy pasted into one example. Please separate and test them.

**Comment by asdine** [comment]
1. This one looks like a regression, thanks for reporting.

2,3 and 4. A lot of these error messages need some love, as well as many parts of the code and the documentation. Genji is still at an early stage of development and spending time on UX when the list of features is so poor didn't seem like a pragmatic strategy, especially when the maintainers are doing this for free on their spare time. Addressing these people as if they owed you something is also not a good strategy. 
So yes, it is not perfect and "feels just buggy" but eventually it will get better, and, if you want to, we'd be more than happy to take your contributions.

**Comment by Indribell** [comment]
> 2,3 and 4: A lot of these error messages need some love, as well as many parts of the code and the documentation. Genji is still at an early stage of development and spending time on UX when the list of features is so poor didn't seem like a pragmatic strategy, especially when the maintainers are doing this for free on their spare time. Addressing these people as if they owed you something is also not a good strategy.

The maintainers put time into creating this project. The persons reporting these issues also puts time into figuring out the issues.  The unclear messages did *not* help in tracking down several issues when we tried out the code.

Clearly the fact that we worked to find these issues, provided a working examples and pointed out problems, that combined with the original bugs into spending more time into tracking then down.

If this is considered some misguided assault on your honor. Then we apology. 

> So yes, it is not perfect and "feels just buggy" but eventually it will get better, and, if you want to, we'd be more than happy to take your contributions.

We have already seen the response on this project when issues are found, tested and reported. Not all heroes wear capes. Code contributions and issue finding/reporting are **both** contributions. 

These issues is considered closed on our part given the feedback provided.
