### ISSUE TITLE
Shell command can be ended by a semicolon

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#198]
Usually in the shell queries should be ended by a semicolon `;`.
It would be convenient to be able to put a semicolon for commands.
```
genji>.indexes foo;
idx_foo_a on foo(a)
genji>
```

**Comment by u5surf** [comment]
@tzzed Hi, Can I work on this issue? 
I assume that `.exit` and `.help` add simply the condition with semicolons in switch-case. 
OTOH, `.indexes` and `.tables` should remove the suffix of their argument (`in[1]`) if they have the semicolon suffix.
