### ISSUE TITLE
Encryption, Backup and Restore working with Genji 

### ISSUE THREAD

**Issue by joe-getcouragenow** [genjidb/genji#204]
We have some of it working. Will have rest of it done in a day or 2 i think.

It would be good to PR it into genji i think. But up to you.

It works off a CLI that is backed by a GRPC. Why ? So can do manage the DB locally or remotely.

The CLI is code gen generated off the GRPC. We do this with all GRPC stuff. It is free and keeps the code smell down.
And because its protobuf its version evolution tolerant so that if the CLI and Server are not the same version it all still works even is the API has changed.

here is an example:
https://github.com/getcouragenow/packages/blob/master/sys-account/server/cmd/authclient/client.go
In the folder rpc2 the CLI code is there with the GRPC.

If you like it them the genji REPL / CLI can also be done this way.
This solves the problem of interacting with the DB while its running too btw which is something that i did not like with the current CLI.

Can chat to us here btw: https://t.me/getcouragenow_dev

@cloudwebrtc

**Comment by asdine** [comment]
This issue is too broad and doesn't explicitly describe the issue or enhancement proposed, like this one https://github.com/genjidb/genji/issues/201.
I'm closing this one but please reopen or create a new one if you want to discuss about something specific.
