### ISSUE TITLE
Should be able to cast null type into array

### ISSUE THREAD

**Issue by shravanshetty1** [genjidb/genji#211]
the array should be nil

**Comment by asdine** [comment]
That's already supported, isn't it?

```sql
genji> SELECT CAST(NULL AS ARRAY);
{
  "CAST(NULL AS ARRAY)": null
}
```

Could you give me more details?

**Comment by shravanshetty1** [comment]
when i do struct scan, if a field of the struct is an array - while value in the db is nil this error will be created. This should be a good first issue

**Comment by shravanshetty1** [comment]
```// CastAsArray casts according to the following rules:
// Text: decodes a JSON array, otherwise fails.
// Any other type is considered an invalid cast.
func (v Value) CastAsArray() (Value, error) {
	if v.Type == ArrayValue {
		return v, nil
	}

	if v.Type == TextValue {
		var vb ValueBuffer
		err := vb.UnmarshalJSON([]byte(v.V.(string)))
		if err != nil {
			return Value{}, fmt.Errorf(`cannot cast %q as array: %w`, v.V, err)
		}

		return NewArrayValue(vb), nil
	}

	return Value{}, fmt.Errorf("cannot cast %s as array", v.Type)
}
```

If value is nil cannot be cast to array - code in file `document/cast.go`

**Comment by asdine** [comment]
I think the issue comes from [document.StructScan](https://sourcegraph.com/github.com/genjidb/genji/-/blob/document/scan.go#L332:1-348:44), not from the cast function.
`StructScan` should be more forgiving when scanning null values

**Comment by shravanshetty1** [comment]
@asdine structScan is calling the cast function - thats why i linked it - should help the person who will fix it!
