### ISSUE TITLE
Expose the __genji_indexes table

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#214]
When we get Indexes of a table by using the following `func (t *Table) Indexes() (map[string]Index, error) `  that called by the following command, the order is randomized.
```
genji>.indexes test
idx_b on test(b)
idx_c on test(c)
idx_a on test(a)
genji> .indexes test;
idx_a on test(a)
idx_b on test(b)
idx_c on test(c)
```
expected behaviour:
```
genji> .indexes test;
idx_a on test(a)
idx_b on test(b)
idx_c on test(c)
genji> .indexes test;
idx_a on test(a)
idx_b on test(b)
idx_c on test(c)
```

**Comment by asdine** [comment]
For this command, I think we should do the same as for the `.tables` command, i.e. exposing a `__genji_indexes` table and use it as the API.
The `database` package is "optimized" for internal use and eventually it would make sense to move it under an `internal` package. I'm not sure we should let other programs access it.
Until we reach that point, it's preferable to avoid using it from the `cli` package and provide a proper SQL API for it to query.

**Comment by tzzed** [comment]
Even if we expose the `__genji_indexes` table we get the randomized for `.indexes table_name` because of the returned `map[string]Index` that give an unordered map.
I think the best way is to change the returned type or order the map.

**Comment by asdine** [comment]
Actually, exposing the `__genji_indexes` table is basically exposing the [index store](https://github.com/genjidb/genji/blob/9da693665fe93d3fcfdffe3312a48712fc40023f/database/config.go#L437) as a table, the same way we did with the [tableInfoStore](https://github.com/genjidb/genji/blob/9da693665fe93d3fcfdffe3312a48712fc40023f/database/config.go#L305-L318). This wouldn't use the `table#Indexes` method.

**Comment by tzzed** [comment]
I understood that. After some investigation  I found what was confused. Thanks @asdine
