### ISSUE TITLE
Add support for embedded structs to document.NewFromStruct

### ISSUE THREAD

**Issue by shravanshetty1** [genjidb/genji#225]
```
type Embedded struct {
	Id string
}
type Example1 struct {
	*Embedded
}
type Example2 struct {
	Id string
}
```

`select * from examples where id = ?` will fail for the first struct but pass for the second struct - am i doing something wrong?

**Comment by asdine** [comment]
> am i doing something wrong

No, it's just that embedded structs are not supported yet. For now, I advise to avoid them until we add that support.
