### ISSUE TITLE
Display DOUBLES  with a decimal point

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#237]
Doubles with `.0` decimal is currently printed as `integer` it should be displayed as double.
```SQL
CREATE TABLE foo (a DOUBLE NOT NULL, b DOUBLE NOT NULLl);
INSERT INTO foo VALUES {"a": 2.0, "b": 3.1};
SELECT * from foo;
{
  "a": 2,
  "b": 3.1
}
```

expected 

```SQL 
SELECT * from foo;
{
  "a": 2.0,
  "b": 3.1
}
```

**Comment by Amirhossein2000** [comment]
Hi
I want to work on this issue.
I think you want this only in Genji shell, true?

**Comment by asdine** [comment]
It must be done in the document package. Basically there is a special type named [jsonDocument](https://github.com/genjidb/genji/blob/5a3cc7be3783457ed96050d7e7c1369efbaadafb/document/document.go#L430-L463) that manually turns a document into json.
Then it calls the [MarshalJSON ](https://github.com/genjidb/genji/blob/5a3cc7be3783457ed96050d7e7c1369efbaadafb/document/value.go#L243:16) method of each value, which might be the culprit.

**Comment by Amirhossein2000** [comment]
It's Done now,
I used this https://stackoverflow.com/questions/52446730/stop-json-marshal-from-stripping-trailing-zero-from-floating-point-number/52446854 to fix this.
