### ISSUE TITLE
Explicit message error for table that doesn't exist

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#238]
Currently when we request a  table that doesn't exist we got the error `table not found`.
This can be complicated to debug especially at the API's level.
I think we should be more explicit
``` SQL
genji> SELECT * FROM foo; 
table not found
genji>
```

```SQL
sqlite> SELECT * FROM foo;
Error: no such table: foo
sqlite>
```

**Comment by carlosfrodrigues** [comment]
Hello, I can take it! Could you assign this issue to me?

**Comment by asdine** [comment]
@carlosfrodrigues Done!
