### ISSUE TITLE
Possibility to create in-memory db - programmatically ?

### ISSUE THREAD

**Issue by nmondal** [genjidb/genji#259]
Hi, 
This is pretty neat!
I just wanted to check if we can have programmatic access to the in memory db?
The doc is not very clear on that!
Great work!

**Comment by yaziine** [comment]
Yes, this is possible by doing this:
```go
db, err := genji.Open(":memory:")
if err != nil {
   // handle the error
}
defer db.Close()
```

Btw, this is written in the [README](https://github.com/genjidb/genji#using-the-memory-engine). Let me know if something is not clear.

**Comment by asdine** [comment]
Closing this, don't hesitate to reopen if needed
