### ISSUE TITLE
Add IF EXISTS/IF NOT EXISTS clause for DROP/CREATE TABLE statement

### ISSUE THREAD

**Issue by tdakkota** [genjidb/genji#265]
It would be nice to be able to use queries like:
```SQL
CREATE TABLE IF NOT EXISTS foo;
DROP TABLE IF EXISTS foo;
```

**Comment by asdine** [comment]
It is actually already supported. The documentation doesn't contain an API reference which makes it difficult to know if a feature is supported or not, sorry about that. It takes a lot of time to write complete documentation during the development but we'll eventually get there.
I'm closing this, please re-open if needed.
