### ISSUE TITLE
multi caller access to genji db badger

### ISSUE THREAD

**Issue by gedw99** [genjidb/genji#266]
It would be awesome if genji badger can be used in a server also.

I use it in a client and its fine, but i would like to also use it in a server that has a GRPC API.

From what i can see the only change required is to add the mutex locks, like the memory engine does.

So we would just have to implement the locks for the 7 functions in badger DB the same as is done in the memory engine.

For example:

Begin of Memory engine has the mutex lock.
https://github.com/genjidb/genji/blob/master/engine/memoryengine/engine.go#L35

Begin of Badger engine does not the mutex lock.
https://github.com/genjidb/genji/blob/master/engine/badgerengine/engine.go#L35

Not sure if the new Context proposal has any relationship to this area.

**Comment by asdine** [comment]
Could you give more details about what is preventing you from using Genji with Badger in a server? If it's about handling concurrency, the badger engine doesn't need the mutex, as concurrency is directly handled by Badger itself.

**Comment by gedw99** [comment]
Ok let me get a proper example done to show you.

**Comment by gedw99** [comment]
Ok we have a benchmark now and it looks good thankfully.

````

Summary:
  Count:        1000
  Total:        201.29 s
  Slowest:      15.13 s
  Fastest:      12.25 s
  Average:      20.04 s
  Requests/sec: 4.97

Response time histogram:
  12253.115 [1] |∎∎∎∎∎∎∎∎∎∎∎∎∎
  12541.298 [3] |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  12829.481 [0] |
  13117.664 [0] |
  13405.847 [0] |
  13694.029 [0] |
  13982.212 [0] |
  14270.395 [0] |
  14558.578 [0] |
  14846.761 [0] |
  15134.943 [2] |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎

Latency distribution:
  10 % in 12.25 s 
  25 % in 12.32 s 
  50 % in 12.33 s 
  75 % in 15.12 s 
  90 % in 15.13 s 
  95 % in 15.13 s 
  99 % in 15.13 s 

Status code distribution:
  [Unknown]            1 responses     
  [OK]                 6 responses     
  [DeadlineExceeded]   993 responses   

Error distribution:
  [1]     rpc error: code = Unknown desc = Transaction Conflict. Please retry   
  [993]   rpc error: code = DeadlineExceeded desc = context deadline exceeded   

````

Will share this with genji of course.

First we want to make it into a matrix of benchmarks with different params and work out the timeouts and transactions errors, so we have a good architectural understanding of the slight changes that might be needed.

But i think all the changes are on our side actually.

**Comment by gedw99** [comment]
Maybe also some golang process stats to go along with the bench too. 
Can then see where the HotSpots are and see if there are changes in genji that might be worth doing.

**Comment by gedw99** [comment]
Closing as original issue is fixed
