### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by Hendler** [genjidb/genji#287]
As a novice in building WASM apps,  is the reason that there is a flag to prevent WASM compilation with `+build !wasm`? 
Are there examples of embedding Genji in a WASM app? Thank you!

**Comment by asdine** [comment]
There is an ongoing project to embed Genji in the browser using wasm, it's using TinyGo but it's not stable yet: https://github.com/genjidb/genji.js
The build tags are there to prevent compiling certain features to wasm because of their incompatibility.

**Comment by asdine** [comment]
Closing this, don't hesitate to reopen if needed
