### ISSUE TITLE
Insert operation is very slow

### ISSUE THREAD

**Issue by SeniorPlayer** [genjidb/genji#299]
I have tested insert and query performance using genji.
When using boltdb as database engine, the insert speed is about 83/s. 
When using badger, it's a little better, the insert speed is about 1700/s.

select query (160k records) :
badger: 220ms/op (table no index) ， 0.5ms/op (table with index)
Bolt: 110ms/op (table no index)  11ms/op (table with index)

I also tested the database performance of boltdb and badger. The result is:
Keysize:22bytes  ValueSize:512bytes  Num:2M
Badger write 280K per second
Boltdb write 20K per second

RandomRead (2M records)
Badger :         1166 ns/op            1061 B/op         19 allocs/op
Boltdb:   644 ns/op             266 B/op          8 allocs/op

Iterate on 2M keys  and Values , valueSize 512bytes
Badger : 1130ms
Boltdb:  160ms

A comparison with mysql:
Innodb write 3200/s,  query 60ms (no index)
Myisam write 9400/s, query 30ms (no index)

So I think genji should improve performance, and we can use it in more places.

**Comment by cbrake** [comment]
thanks for the performance reports -- very interesting. What type of application do you have in mind that the current performance is not adequate?

Have you profiled to see where the bottlenecks are?

**Comment by Wumms** [comment]
Slow inserts here as well. Results (averaged from inserting 10k pre-build small structs) when using
- boltdb: 80/s (single CPU usage ~10%; profiled bottleneck: boltdb waiting for fsync (syscall))
- badger: 1.7k/s (seems to use only one CPU(?); profiled bottleneck: badger waiting for write (syscall))
- in-memory: 47k/s
Since the query performance seems fine - is it possibility to use bulk inserts (e.g. badgers write batch API [1])?

[1] https://github.com/dgraph-io/badger/issues/869

**Comment by asdine** [comment]
The stats shared above unfortunately don't say much about the conditions of the benchmarks:
- what is the size of the payload?
- what are the queries?
- are you creating a transaction for each write (requires a full disk fsync each time) or running batches of inserts and calculating the average?
- are you using prepared statements?

Next release writes should be quite fast actually, as an example it's about 50 to 70% faster than SQLite (in WAL mode) and there is still room for optimization.
I'm closing this issue but please feel free to reopen if you feel like it's still a problem with the current main branch.
