### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by KudinovKV** [genjidb/genji#300]
When I trying to run `go get github.com/genjidb` get this:

```
cannot find package "github.com/vmihailenco/msgpack/codes" in any of:
        /usr/local/go/src/github.com/vmihailenco/msgpack/codes (from $GOROOT)
        /home/kkudinov/go/src/github.com/vmihailenco/msgpack/codes (from $GOPATH)
```
`github.com/vmihailenco/msgpack` updated for v5. Please update genji to use this package.

**Comment by tie** [comment]
Hi, thanks for the report! We are already using v5 but we need to update import paths for the latest commit (see https://github.com/vmihailenco/msgpack/commit/481cbe1dac1e13384a8115b41af2d84c3e05224c).

Also note that `github.com/vmihailenco/msgpack` release model is incompatible with GOPATH-mode (idiomatic way is to create `v5` directory for the new release, see [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules)). That is, we can’t guarantee that this dependency won’t break in the future with GOPATH-mode. I suggest either migrating to [Go modules](https://blog.golang.org/using-go-modules) or filing an issue in msgpack repo.

**Comment by asdine** [comment]
Closing this, don't hesitate to reopen if needed
