### ISSUE TITLE
Use genji.dev as package import path prefix

### ISSUE THREAD

**Issue by tie** [genjidb/genji#308]
### Proposal

There is a growing number of general-purpose packages in Genji (e.g. `sql/query/glob`). I propose using `genji.dev/` import path prefix instead of `github.com/genjidb/genji/` so that we can (re)map logical package names to their physical location using `go-import` HTML meta tags.

Currently, importing Genji APIs is done as follows
```go
import (
	"github.com/genjidb/genji"
	"github.com/genjidb/genji/document"
	"github.com/genjidb/genji/sql/driver"
	"github.com/genjidb/genji/sql/query/glob"
	// …
)
```
And after the proposed changes
```go
import (
	"genji.dev/document"
	"genji.dev/genji"
	"genji.dev/glob"
	"genji.dev/sql/driver"
	// …
)

```

### Motivation

We’d like to make some general-purpose packages reusable outside of Genji. That is, they should be in a separate Go module that does not depend on Genji internal or external API. Instead of extracting them to their own repos, I think it’s better to keep the development and issue tracking centralized.

See also: https://github.com/genjidb/genji/pull/306#issuecomment-719529182

### Changes

Assuming we want to keep a monorepo with nested modules,

- Start on a separate branch.

- Move current root `github.com/genjidb/genji` package (not go.mod though) to `genji` directory. That would become `genji.dev/genji` import path.

- Move `sql/query/glob` to `glob` directory. Add `go.mod` for this package.

- Update all import paths to use `genji.dev`.

- Add a single `go-import` meta tag to HTML pages on [genji.dev](https://genji.dev) domain.
  See https://golang.org/cmd/go/#hdr-Remote_import_paths
  ```html
  <meta name="go-import" content="genji.dev git https://github.com/genjidb/genji">
  ```

  It looks like we don’t need [`go-source`](https://github.com/golang/gddo/wiki/Source-Code-Links) meta tag, see [golang/pkgsite:internal/source/source.go](https://github.com/golang/pkgsite/blob/211adadab808f6278d1b8905b781e6c98d7ba629/internal/source/source.go#L352-L367).

  Note that multiple meta tags may not match the same import paths (special `mod` vsc is an exception), see [golang/go:src/cmd/go/internal/vcs/vcs.go](https://github.com/golang/go/blob/733c4af41d2e89d18cfb039e0107336a4c1ec220/src/cmd/go/internal/vcs/vcs.go#L987-L1007).

- At this point we should be able to test these changes with local replace directive in go.mod pointing at the latest commit on test branch. Note: disable GOPROXY.
  If everything is working fine, push changes to the main branch.

**Comment by asdine** [comment]
We are now using the `lib/` directory for independent packages and keeping it very simple. Will re-open if the needs become more important in the future. Thanks!
