### ISSUE TITLE
Comparing values against NULL should not return NULL

### ISSUE THREAD

**Issue by tie** [genjidb/genji#309]
### What version of Genji are you using?

Main branch checked out at (currently latest) commit a42cf4e06da3afdce33bcdee7da3e0922e8edb02.

### Does this issue reproduce with the latest release?

Yes, tested with v0.8.0 shell.

### What did you do?

```
CREATE TABLE t;
INSERT INTO t(x) VALUES (NULL);
```

```
SELECT * FROM t WHERE x == NULL;
```

```
SELECT * FROM t WHERE (NULL == NULL);
```

Note that simple `SELECT * FROM t WHERE NULL == NULL` panics due to #283.

### What did you expect to see?

Same as `SELECT * FROM t` since `NULL == NULL`.
```
{
  "x": null
}
```

### What did you see instead?

No matching rows.

### What Go version and environment are you using?

<pre>
$ go version
go version devel +05f5ae74bc Tue Oct 20 15:19:09 2020 +0000 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/tie/gobin"
GOCACHE="/Users/tie/Library/Caches/go-build"
GOENV="/Users/tie/.go/env"
GOEXE=""
GOFLAGS="-trimpath"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tie/.go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tie/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/tie/sdk/gotip"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/tie/sdk/gotip/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/tie/pr/genji/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4p/grbvv3f96zdbm2bjx3z1km4r0000gn/T/go-build286248016=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by asdine** [comment]
This is not a bug, it is by design, as the `=` operator should always return null when compared with null.
To compare with null, you should use the `IS` operator:

Genji:
```sql
genji> CREATE TABLE t(a, b);
genji> INSERT INTO t(a, b) VALUES (1, NULL);
genji> SELECT * FROM t WHERE b == NULL;
genji> SELECT * FROM t WHERE b IS NULL;
{
  "a": 1,
  "b": null
}
```

SQLite:
```sql
sqlite> CREATE TABLE t(a, b);
sqlite> INSERT INTO t(a, b) VALUES (1, NULL);
sqlite> SELECT * FROM t WHERE b = NULL;
sqlite> SELECT * FROM t WHERE b IS NULL;
a|b
1|
```

https://stackoverflow.com/a/9581790/1826232
https://www.postgresql.org/docs/current/functions-comparison.html

**Comment by tie** [comment]
Ah, yeah, my bad. Thanks for pointing that out! Closing the issue since this is by design.
Do we have this behavior documented somewhere?

**Comment by asdine** [comment]
Not much, there is one reference in [comparison operators](https://genji.dev/docs/genji-sql/expressions/#comparison-operators) doc, and one for [arithmetic operators](https://genji.dev/docs/genji-sql/expressions/#the-case-of-null). But nothing very explicit about it yet
