### ISSUE TITLE
Add Bitcask backend

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#31]
KV Store: https://github.com/prologic/bitcask

Currently the master branch is (really) unstable as I'm basically breaking everything with a sledgehammer. The `engine` package though (the one that contains interfaces that need to be implemented) wasn't touch in the master branch so it should be good.

Also, I'd really like to avoid having too many dependencies with Genji (especially because of the store implementations) so I think it should be better if the Bitcask package had its own `go.mod`. In next release, every backends will have their own `go.mod` so users will be able to choose explicitly the store they want to use.
This also means that you'll have to base your work on the `v0.1.0` tag, which is fine I suppose, as I said there aren't that many changes in the engine on the master branch.

Regarding tests, there is a `engine/enginetest` package that contains importable tests that make sure your backend is compatible, you can take a look at the other backends if you need examples.

**Comment by prologic** [comment]
@asdine I have sort of a partial implementation (untested) but there are some things I'm not quite so clear on how to implement and/or whether nor not [Bitcask](https://github.com/prologic/bitcask) as it currently stands is missing any low-level features required to Fulfil a Genji engine?

For example; I'm a bit lost when it comes to the `AscendGreaterOrEqual()` and `DescendLessOrEqual()` interfaces. Bitcask currently supports only basic prefix scans with a prefix to search from (internally uses an adaptive radix tree).

Further Bitcask has no transactions or the concept of multiple stores or buckets. Would I just simulate this in the Genji specific engine?

**Comment by asdine** [comment]
@prologic I had the same situation with the `memory` and `badger` engine. You can have a look at how they both are implemented.

- Multiple stores: When you have a single namespace for the entire database, you can use [prefixes](https://github.com/asdine/genji/blob/master/engine/badger/store.go#L19-L25) and [assign](https://github.com/asdine/genji/blob/master/engine/badger/store.go#L14) each one to a given store.
Then whenever you need to put and get a key you only need to [prefix it](https://github.com/asdine/genji/blob/master/engine/badger/store.go#L37) with the store prefix
- Ascend / Descend: I believe that if You can use `Bitcask.Scan` scans the keys in order, it should work fine with Genji. Here are the [Bolt](https://github.com/asdine/genji/blob/master/engine/bolt/store.go#L53-L63) and [Badger](https://github.com/asdine/genji/blob/master/engine/badger/store.go#L76-L97) implementations
- Transactions: It's a bit trickier. The [memory engine](https://github.com/asdine/genji/blob/master/engine/memory/engine.go#L51) uses a `sync.RWMutex`, that uses `RLock()` for read transactions and `Lock` for write transactions. For rollbacks / commits, it modifies directly the Btree but stores "undo" functions that are [applied](https://github.com/asdine/genji/blob/master/engine/memory/engine.go#L64-L66) if the txn gets rolled back.
This is not ideal as it only allows a single writer at a time but it gets the job done. Since you are using a radix tree, perhaps you can take a look at how Hashicorp's [MemDB](https://github.com/hashicorp/go-memdb) uses MVCC transactions on top of their Radix tree implementation, but I'm not sure how long it would take to implement your own version.
- Testing: To verify the compatibility with Genji, you don't need to write your own tests, you can use the `enginetest` test suite. Here is an [example](https://github.com/asdine/genji/blob/master/engine/badger/engine_test.go) of how I did that with Badger

Let me know if you have any questions

**Comment by prologic** [comment]
Thanks I'll keep plugging away at it. Appreciate the guidance!

**Comment by ivanjaros** [comment]
when i compared performance of bolt, badger and bitcask last year, bitcask was ..... let's say not good. i don't think it is worth the time. bolt and badger cover all the bases

**Comment by prologic** [comment]
> when i compared performance of bolt, badger and bitcask last year, bitcask was ..... let's say not good. i don't think it is worth the time. bolt and badger cover all the bases

Are you able to file an issue on the latest version at https://github.com/prologic/bitcask and demonstrate some numbers? I'm curious to see the results of your findings and how you performed these benchmarks, benchmarks of course being what they are. Thanks! 🙏

**Comment by asdine** [comment]
Closing this, @prologic please feel free to reopen if you want to keep talking about this
