### ISSUE TITLE
Add .save command

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#311]
Add `.save` command to Genji CLI

Synopsis: `.save ?badger? PATH `

Description: Write database into PATH

Usage:

```bash
# run in memory database
genji
# or on-disk database
genji my.db
```

```sql
genji> CREATE TABLE foo;
genji> INSERT INTO foo(a) VALUES (1);
genji> .save foo.db
genji> .save badger foo 
```

```bash
$ ls
my.db foo.db foo/
```

Calling .save on an existing database file or path overwrites it.

**Comment by asdine** [comment]
cc @jhchabran, pinging you so I can assign you

**Comment by jhchabran** [comment]
You can assign me now 👍
