### ISSUE TITLE
Add ORDER BY clause to DELETE statement

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#318]
```sql
DELETE FROM foo ORDER BY a DESC

EXPLAIN DELETE FROM foo ORDER BY a DESC
{
  "plan": "Table(foo) -> Sort(a DESC) -> Delete(foo)"
}
```

It must have the same behavior as SELECT.

The parser already knows how to parse `ORDER BY`:  https://github.com/genjidb/genji/blob/707824da1399f16d9242a8e6bfa17ac50ec353af/sql/parser/select.go#L173

**Comment by jhchabran** [comment]
Taking this one, along #319  and #320 !
