### ISSUE TITLE
Add restore command 

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#321]
```bash
$ genji restore -h
NAME:
   genji restore - Restore a database or a table from a file created by genji dump

USAGE:
   genji restore dumpFile dbPath

DESCRIPTION:
  The restore command can restore a database or a table from a text file.

  $ genji restore dump.sql my.db 

OPTIONS:
   --help, -h                show help (default: false)
```

**Comment by yaziine** [comment]
I think it should take more flags for specifying the table and the engine to use:
```
$ genji restore -h
NAME:
   genji restore - Restore a database or a table from a file created by genji dump

USAGE:
   genji restore [options] dumpFile dbPath

DESCRIPTION:
  The restore command can restore a database or a table from a text file.

  $ genji restore dump.sql my.db 

OPTIONS:
   --engine, -e            name of the engine to use, options are 'bolt' or 'badger'. Default to 'bolt'
   --table, -t             name of the table to restore. Default to all tables
   --help, -h              show help (default: false)
```

**Comment by tzzed** [comment]
I think the `--table` option is not usefull in this case. Restoring a table from a "dump" file seems weird. In my point of view, it will be more simplest and usefull in a `.restore` command.
What is the expected behavior if the `dbPath` exists? Should the file be overwritten? return an error?

**Comment by asdine** [comment]
> I think the --table option is not usefull in this case

Agreed

> What is the expected behavior if the dbPath exists? Should the file be overwritten? Return an error? It currently returns error: table already exists for the CREATE query.

I think this is good enough, we can leave it like that
