### ISSUE TITLE
deadlock after committing a read-only transaction

### ISSUE THREAD

**Issue by yaziine** [genjidb/genji#335]
Deadlock after committing a read-only transaction. But there is no error if I rollback it.

Should read-only tx be rollbacked only?

```go
db, err := genji.Open("test.db")
if err != nil {
	log.Fatal(err)
}
defer db.Close()

err = db.Exec("CREATE TABLE IF NOT EXISTS foo(name text)")
if err != nil {
	log.Fatal(err)
}

tx, err := db.Begin(false)
if err != nil {
	log.Fatal(err)
}
_, err = tx.Query("SELECT * FROM foo")
if err != nil {
	log.Fatal(err)
}
tx.Commit()

err = db.Exec("INSERT INTO foo(name) VALUES ('gon')")
if err != nil {
	log.Fatal(err)
}
```

**Comment by asdine** [comment]
Commit is not allowed on read-only transactions, if you check the error returned by `tx.Commit` it should be not nil.
I'm closing this and I will update the documentation to reflect that, don't hesitate to reopen if needed.
