### ISSUE TITLE
database/sql ORDER BY error

### ISSUE THREAD

**Issue by hynd** [genjidb/genji#338]
Loving genji so far - thanks!

### What version of Genji are you using?
<pre>
v0.9.1-0.20210105060628-b0134220aac3
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

When using the database/sql driver, adding an `ORDER BY x` clause (with or without a direction) to a filtered `SELECT` query returns an error.  The same `SELECT` with `ORDER BY` clause using the Genji API works as expected.

Minimal example:
https://play.golang.org/p/F5bfkULNCWd

### What did you expect to see?

An dump of a and b values, ordered by a.

### What did you see instead?

`ERROR 1: sql: expected 0 destination arguments in Scan, not 2` unless the `ORDER BY a` is removed.

### What Go version and environment are you using?

<pre>
$ go version
go version go1.15.6 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/Code/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/user/Code/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/user/Code/gocode/src/github.com/hynd/genjitest/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3r/_jv56wbj2xb6gwh9pkv9y62cg1_7cm/T/go-build810324326=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by tzzed** [comment]
@asdine can I take this one ?

**Comment by asdine** [comment]
Sure!
Here are some hints:

The driver assumes that the stream.ProjectOperator [is always the last node of the stream](https://sourcegraph.com/github.com/genjidb/genji/-/blob/sql/driver/driver.go#L284-289), which is not true:

```sql
genji> EXPLAIN SELECT a, b FROM foo WHERE c > 10;
{
  "plan": "seqScan(foo) | filter(c > 10) | project(a, b)"
}

genji> EXPLAIN SELECT a, b FROM foo WHERE c > 10 ORDER BY d;
{
  "plan": "seqScan(foo) | filter(c > 10) | project(a, b) | sort(d)"
}

genji> EXPLAIN SELECT a, b FROM foo WHERE c > 10 LIMIT 10;
{
  "plan": "seqScan(foo) | filter(c > 10) | project(a, b) | take(10)"
}
```

As you can see in the examples above, in the first query the last node is `project(a, b)`, while for the other ones it's not (respectively, `sort(d)` and `take(10)`.

The driver must be modified so that it loops over the stream until it finds the project operator, then extract the fields from it.

**Comment by tzzed** [comment]
This is what I have seen.
