### ISSUE TITLE
Binlog

### ISSUE THREAD

**Issue by joeblew99** [genjidb/genji#34]
Is there the ability to implement binlog equivalent ?
This is for subscriptions use case .

This library is really nice to use. Great work

**Comment by joeblew99** [comment]
Looks like maybe we can just tap into the "Table" class and pump a record out on Insert, Update or Delete ?

**Comment by asdine** [comment]
Hey @joeblew99 
Thank you for your feedback!

About the binlog, I think it could be a good addition but I'd wait for a next version because I'm working on adding the SQL layer first, which makes me rework a lot of existing APIs.

Also, I'm still wondering if it should be engine specific (meaning that some engines would and some wouldn't implement it) or something that would be in Genji directly.

Do you have examples of use cases? CDC perhaps?

**Comment by joeblew99** [comment]
@asdine 

Sorry about not getting back to this. WOW congrats on getting this far with genji. This is now really useful and we are starting to explore using it for one of our projects. 

Yes the WAL can be used for CDC but also other things too...

For example genji has no HA story yet. Once a WAL is there then we could use LiftBridge to do different HA strategies. For example DGraph has the notion of Zero and Alpha nodes and can shard the data and keep shards with 3 replicas. We would use a CDC / Message queue like LiftBridge to do that. LiftBridge is doing the Raft stuff, and not the Genji database but then effectively makes genji HA. 
Because you have a SQL layer and drivers to abstract access to the raw db ( bolt, badger, etc) its possible then to have a generic WAL. For example Cockroach's data structure. Or just the CUD events ( Create, Update, Delete) streaming into LiftBridge.

Lift Bridge is pure GRPC APi too. Its not language specific and so its reusable for different languages !
With the SQL gen in genji, we have a DB that can be use also by non golangers. The SQL gen would have to be a compiler as a Service approach i know. But still not half bad.

It also means that others can tap LiftBridge to do the other CDC related use cases.
For example i use the This golang geo database: https://github.com/tidwall/tile38
So i would need to tap the WAL in genji for certain changes to update the tile38.

Another CDC use case is Materialised Views.
Say you have a complex data structure and you want a View that uses that complex data structure to make a simple View. Maybe for some analytics.
SO i can tap the WAL to keep my Materialised View up to date.
Then i would tap the WAL on the Materialised view to keep clients up to data that have subscribed to it.
At the moment i use NATS and Lift Bridge for doing the subscription stuff. A User with 3 devices is a good  example. LiftBridge and NATS can handle keeps a users many devices up to data even if each device is at a different stage in keeping up to data ( like that old tablet you have not turned on for a month).

Me and the others here are curious what you think about the above aspects. We could help do some of this but we do not want to work against what your Techncial roadmap is of course.

Maybe we could start with WAL and then about using LiftBridge to receive the WAL ?
That would get the basic infrastructure in place to explore the various use cases i wrote about above.
But also allow us to see what other use cases people have..

**Comment by asdine** [comment]
@joeblew99 Thank you for these examples, I think this could be great to have some HA for Genji someday, however I believe it's still a bit too early to think about it.
There are quite a few basic features that Genji doesn't have and I'd like to put all my energy on those first.
In the meantime, we can talk about it on [Slack](https://gophers.slack.com/messages/CKPCYQFE0) if you are interested

**Comment by asdine** [comment]
Closing this as this is not planned for now. Happy to reopen it when we implemented more features.

**Comment by kcmvp** [comment]
it's really a cool project. After some evaluation about its features. I also want this binlog feature. my my case I need to use it sync data between nodes.
