### ISSUE TITLE
msgpack codec encodes all integers type into int64 rather than picking the right type

### ISSUE THREAD

**Issue by jhchabran** [genjidb/genji#349]
### What version of Genji are you using?

The `main` branch.

<pre>
$ genji version
Genji v0.11.0
Genji CLI (devel)
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

(Preamble, I know that all sql `INT*` types are just `document.IntegerValue` under the hood, I'm talking at codec level here). 

While reading the msgpack codec, my eye was caught by https://github.com/genjidb/genji/blob/8e580748aedb60ec007df65013936287ec5dcc21/document/encoding/msgpack/codec.go#L100-L111 which says that the int types will be encoded using they msg pack counterpart, ie int8 -> int8, but the code didn't look like it handles those case. 

While digging, I found out that:

- all integers end up as int64 anyway when reaching the codec 
- even if fed an int8, EncodeValue will end up using an int64 in msgpack because it uses  `case document.IntegerValue: return e.enc.EncodeInt64(v.V.(int64))` under the hood. 

**➡️ It looks to me that the [comment](https://github.com/genjidb/genji/blob/8e580748aedb60ec007df65013936287ec5dcc21/document/encoding/msgpack/codec.go#L100-L111) is wrong and that the int64 encoding for all ints is actually on purpose as per what the decoder does here: https://github.com/genjidb/genji/blob/main/document/encoding/msgpack/codec.go#L221**

❓ @asdine Is that a deliberate choice here? Is it related to how msgpack work somehow? Otherwise it looks like it's a rather low hanging fruit to have more compact integer storage. 

---

```go
package main

import (
	"bytes"
	"context"
	"fmt"
	"os"

	"github.com/genjidb/genji"
	"github.com/genjidb/genji/engine"
	"github.com/genjidb/genji/engine/boltengine"
	mp "github.com/vmihailenco/msgpack/v5"
)

func main() {
	// so we always get the same store id every run, see line 52
	_ = os.Remove("test.db")

	db, err := genji.Open("test.db")
	if err != nil {
		panic(err)
	}

	err = db.Exec("CREATE TABLE foo ( a INTEGER )")
	if err != nil {
		panic(err)
	}

	err = db.Exec("INSERT INTO foo (a) VALUES (?)", 2)
	if err != nil {
		panic(err)
	}

	err = db.Close()
	if err != nil {
		panic(err)
	}

	ng1, err := boltengine.NewEngine("test.db", 0o600, nil)
	if err != nil {
		panic(err)
	}

	etx, err := ng1.Begin(context.Background(), engine.TxOptions{})
	if err != nil {
		panic(err)
	}

	//  func (t *tableInfoStore) Insert(tx *Transaction, tableName string, info *TableInfo) error {
	//		(...)
	//      fmt.Println(info.storeName)
	store, err := etx.GetStore([]byte{116, 1})
	if err != nil {
		panic(err)
	}

	it := store.Iterator(engine.IteratorOptions{})
	it.Seek(nil)

	item := it.Item()

	k := item.Key()

	b, err := store.Get(k)
	if err != nil {
		panic(err)
	}

	fmt.Println(b)

	dec := mp.NewDecoder(bytes.NewReader(b))

	ii, err := dec.DecodeInterface()
	if err != nil {
		panic(err)
	}

        // ➡️ ### What did you expect to see? ⬅️
	fmt.Printf("%$v\n", ii)
}

```

### What did you expect to see?

```
[129 161 97 2]
map[%!$(string=a):%!$(int8=2)]v
```

### What did you see instead?

```
[129 161 97 211 0 0 0 0 0 0 0 2]
map[%!$(string=a):%!$(int64=2)]v
```

### What Go version and environment are you using?

<pre>
$ go version
go version go1.15.8 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/tech/code/bin"
GOCACHE="/Users/tech/Library/Caches/go-build"
GOENV="/Users/tech/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tech/code/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tech/code"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/tech/.asdf/installs/golang/1.15.8/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/tech/.asdf/installs/golang/1.15.8/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tech/code/src/github.com/genjidb/play/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xl/dfsx6nzs4cb2y40m555mlfjh0000gn/T/go-build230471881=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by asdine** [comment]
The comment is outdated yes, Genji used to have multiple integer types, one per integer size, and the comment use to reflect that.
Regarding the integer size, this is definitely a bug and we should use EncodeInt instead of EncodeInt64, good catch!

**Comment by jhchabran** [comment]
Great then! Do you want to fix that in the current release, in which case I can open up a PR right away or later on?

**Comment by asdine** [comment]
Of course, please open one anytime you see fit

**Comment by jhchabran** [comment]
See the fix in the PR referenced above!

Since I was there, I also looked at the compact float settings, from which the size aspect would benefit greatly, especially in the use case that involves dumping JSON without a schema into a DB. 

It currently breaks the tests because it will turn some doubles into ints when decoding (msgpack assumes you always know into what you're decoding, so it's on us, the caller side to turn those ints back into doubles if that's what we want). 

@asdine I assume you made the choice of using double everywhere unless a constraint says that a field is an integer since JSON uses double for everything right?

Because the `document.Decoder` has no knowledge of the `Document` it's decoding into, we cannot trivially implement a fix though (decoder could have checked if there was a constraint that tells that something is an int, if not, convert every number as a double). 

That's probably too much of a change, for now; I also have no idea how common is that use case. It's just that if we had to break the storage compatibility, better do it once that twice 😆 !

**Comment by asdine** [comment]
That could be worth investigating yes, as it would be a great win in terms of space. The only thing that worries me about this is:

1. performance: additional check to see if it should be decoded as an int or double
2. codec complexity: now the codec must be aware of the constraints

If we can find a solution for 1 at least, that would be a great win!

**Comment by asdine** [comment]
After investigation, it turns out it is possible to encode a double as integer, using a custorm ext code (https://github.com/genjidb/genji/commit/e4aecc5dc8bee2ae29f6f9111598cc94dc2d1a19) but the overall size of the database doesn't change even with a table with 1M doubles.
Closing this as the original issue has already been fixed!
