### ISSUE TITLE
Possible to add lmdb to backend store?

### ISSUE THREAD

**Issue by hiqsociety** [genjidb/genji#375]
1. Possible to add lmdb to backend store?
2. Can switch msgpack to greenpack? https://github.com/glycerine/greenpack

**Comment by asdine** [comment]
1. Maintaining multiple engine implementation requires lots of work, so we won't be adding any for the moment. However you are free to [implement](https://github.com/genjidb/genji/blob/78535320ddabcf4b8663a172cee7a917462a6997/engine/engine.go#L32-L39) your own and share it to the world in a separate repo
2. I don't see a reason why, one is maintained the other is not.
