### ISSUE TITLE
func (db *DB) Query(q string, args ...interface{}) (*query.Result, error) {}    Deadlock occurred

### ISSUE THREAD

**Issue by tiezhong2004** [genjidb/genji#379]
### What version of Genji are you using?

<pre>
$ genji v0.11.0

</pre>

### Does this issue reproduce with the latest release?

Yes

### What Go version and environment are you using?

<pre>
$ go 1.15.6 linux/amd64

</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

**Comment by tiezhong2004** [comment]
[
![Uploading Deadlock occurred.gif…]()
](url)

**Comment by tiezhong2004** [comment]
[
![Deadlock occurred](https://user-images.githubusercontent.com/10120349/113583661-848e2d80-965c-11eb-83dc-ab34e4c4646b.gif)
](url)

**Comment by tiezhong2004** [comment]
[
![Deadlock occurred](https://user-images.githubusercontent.com/10120349/113586604-4abf2600-9660-11eb-93a4-b7b91649f1fd.gif)

](url)

**Comment by tiezhong2004** [comment]
![image](https://user-images.githubusercontent.com/10120349/113593911-90ccb780-9669-11eb-958f-c4dd864a76db.png)

**Comment by tiezhong2004** [comment]
[
![image](https://user-images.githubusercontent.com/10120349/113594065-bf4a9280-9669-11eb-91bc-c7dd0be9d926.png)
](url)

**Comment by asdine** [comment]
@tiezhong2004 Can you share some code so we can see where the deadlock happens?
Also, did you start a query before close the result for the previous one?

**Comment by asdine** [comment]
Closing this issue for now as there is no way to debug it. @tiezhong2004 please feel free to reopen if you have more information.
Gifs are not useful for us to debug, a simple `main` function or a playground would be better

**Comment by tiezhong2004** [comment]
var engine *genji.DB

func CreateEngine(path string, config *config.Database) (err error) {
	datasource := config.Url
	//dbType := config.Type
	if !strings.HasPrefix(datasource, "/") {
		datasource = filepath.Join(path, datasource)
	}
	//logs.Infof("connect %s %s", dbType, datasource)
	logs.Infof("connect %s", datasource)

	notExists := files.NotExist(datasource)
	engine, err = genji.Open(datasource)
	if err != nil {
		return err
	}
	if notExists {
		err = createTables()
		//engine.Close()
	}
	//engine.Close()
	return
}



//添加新节点token
func (self *nodeDao) ModifyToken(key, token string) error {
	doc, err := engine.QueryDocument("SELECT * FROM node WHERE keyword = ?", key)
	if err != nil && doc != nil {
		if v, _ := doc.GetByField("keyword"); v.V.(string) == key {
			err = engine.Exec(`UPDATE node SET token = ?`, token)
			return err
		}
	} else {
		node := new(Node)
		node.Key = key
		node.Token = token
		node.Time = Timestamp()
		node.Status = NodeStatusOutline
		err = engine.Exec(`INSERT INTO node VALUES ?`, node)
		if err != nil {
			return err
		}
		return nil
	}
	return nil
}
