### ISSUE TITLE
genji restore very slow on large dumps

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#381]
Because `genji dump` wraps everything between `BEGIN` and `ROLLBACK`, it takes a very long time to restore large databases (several 100s of Mb).
Investigate how other databases deal with this issue, by generating a big sqlite database for example.

**Comment by tzzed** [comment]
@asdine is still right after your optimization? there is a relation between the optimizations and this issue?

**Comment by asdine** [comment]
Fixed by 36eb6ba47a8a9ab7c6e3a69f958fe9af289034f1, we can now apply arbitrary large transactions to the database
