### ISSUE TITLE
Add support for multiline comment

### ISSUE THREAD

**Issue by jhchabran** [genjidb/genji#394]
After having experimented a bit with a simpler way to write integration tests (see #380), it has become apparent that the single-line comments can get in the way of writing the expectations, especially with the alignment.

Multiline comments would enable to address that specific point. 

It is quite common (https://www.sqlite.org/lang_comment.html) to have those defined as `/* ... */`.

**Comment by jhchabran** [comment]
Closing this, they're already supported as per https://github.com/genjidb/genji/blob/main/sql/scanner/scanner.go#L134-L139

```
genji> select /* trololollo */ 1+1;
{
  "1+1": 2
}
genji>
```

**Comment by asdine** [comment]
I had completely forgotten that we already had multi-line comments 🤣
