### ISSUE TITLE
panic on genji restore 

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#395]
### What version of Genji are you using?

<pre>
$ genji version
Genji (devel)
Genji CLI (devel)
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```sh
genji restore
```

### What did you expect to see?

see genji help

### What did you see instead?

```sh
panic: runtime error: index out of range [-1]
```
### What Go version and environment are you using?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/touk/Library/Caches/go-build"
GOENV="/Users/touk/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/touk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/touk/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/touk/workspace/genji/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ls/dpdwm5q966558yb487lfvn9r0000gn/T/go-build2545503002=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

**Comment by jhchabran** [comment]
```
~/code/src/github.com/genjidb/genji  main› genji restore
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/urfave/cli/v2.(*args).Get(0xc0002dfca0, 0xffffffffffffffff, 0x6, 0x464dcb7)
	/Users/tech/code/pkg/mod/github.com/urfave/cli/v2@v2.3.0/args.go:23 +0x5f
github.com/genjidb/genji/cmd/genji/commands.NewRestoreCommand.func1(0xc00015aac0, 0x0, 0x0)
	/Users/tech/code/src/github.com/genjidb/genji/cmd/genji/commands/restore.go:39 +0x135
github.com/urfave/cli/v2.(*Command).Run(0xc00014f200, 0xc00015a980, 0x0, 0x0)
	/Users/tech/code/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc00011f6c0, 0x46f2e90, 0xc000130008, 0xc000138000, 0x2, 0x2, 0x0, 0x0)
	/Users/tech/code/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/tech/code/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/Users/tech/code/src/github.com/genjidb/genji/cmd/genji/main.go:13 +0x67
```

This [line](https://github.com/genjidb/genji/blob/main/cmd/genji/commands/restore.go#L39) doesn't perform a length check before accessing the slice, causing the crash.
