### ISSUE TITLE
Go Fuzz configuration issue

### ISSUE THREAD

**Issue by jhchabran** [genjidb/genji#397]
https://github.com/genjidb/genji/pull/396/files#diff-be7391fdfbc99cc9bad8f2118c42c4a0f76666414f9d5f5ce95502349c05394cR14

@tie We tried to fix the problem differently but after spending some time on it, we didn't find something conclusive. Do you think you could have a look? 

Side note: it appears that the bug forcing us to use go 1.14.9 for go fuzz has been fixed. I did try to update it but ran into another issue. For the context, the generated tests present in #396 need Go embeds and thus Go 1.16. To move forward, we committed those for now.

**Comment by tie** [comment]
As far as I know, go-fuzz doesn’t work with embed package right now.

Could you please explain why we need embed package in tests? I though that the usual pattern is to read the file from `testdata` directory.

That said, I’ve opened #399 so that we can move forward with minimum supported Go version. I’ll port the current seed corpus to the new format tomorrow.

**Comment by tie** [comment]
@jhchabran I’ve migrated the seed corpus to new format and moved that to main repo. There is still a TODO in genjidb/go-fuzz-corpus#2 for committing corpus cache to go-fuzz-corpus repo, but let’s leave it for another PR.

**Comment by tie** [comment]
@jhchabran regarding test scripts, do we really need to _generate_ tests? I think it would be better to put scripts in `testdata/sqltest` and have a test helper to run these files in `t.Run("foo_bar.sql", …)` callback.

**Comment by jhchabran** [comment]
@tie the generated tests have a few advantages, there is no intermediate layer; a single test can be run over and over and can be manually updated while trying to understand what is wrong; the feedback loop can be shortened because it's possible to run only a single test and the most important in my eyes, you can fire up a debugger with a breakpoint very easily. 

I'd argue that in 99% of the cases, the approach you suggested is better but here we can pay the tooling price because there are tons of cases that we want to cover and the ability to debug that one failing test case quickly is really useful.

I hope that we'll be able to remove the generated test soon, while not that problematic, it doesn't look very clean 😄 !
