### ISSUE TITLE
Genji js to use indexdb 

### ISSUE THREAD

**Issue by gedw99** [genjidb/genji#405]
### Motivation

https://github.com/JohnStarich/go-wasm/tree/master/internal/indexeddb

Will allow genji.js to have an indexdb store , like the currently badger dB store.

wonder if golang leveldb  is a good indexdb emulator ? I read somewhere that there is a relationship between leveldb and indexdb.

The indexdb btw is used as a file system abstraction so that golang wasm has a file system to talk to. So it essentially can be used as a blob store for golang wasm apps too.

It does not work with tinygo . But I think it’s just a matter of time and help from others .

**Comment by asdine** [comment]
This is indeed part of a long term plan for genji.js. I'm closing this issue as this is not directly related to Genji, please follow the genjidb/genji.js repo instead 👍🏼

**Comment by gedw99** [comment]
Hey @asdine 

Code is now here:
https://github.com/hack-pad/go-indexeddb

He refectored it out to make it reusable for all. and so can be a driver for Genji if need be.
I am playing with it  with GIOUI. Its quite fun to be pure go...
