### ISSUE TITLE
Support key-only iteration

### ISSUE THREAD

**Issue by drauschenbach** [genjidb/genji#41]
It's unclear from the documentation whether key-only iteration is supported.

For example, in an `Iterate(func(recordId []byte, r record.Record) error` function call, does the `r` variable contain a facade that will lazy-load the value, or is the value already loaded?

In the underlying storage engines, key-only iteration is specifically called out as a first class use case (because it's so important, especially for Badger), so I think that makes sense to also document and support in a higher level library like this.

**Comment by asdine** [comment]
Currently, both the key and the value are fetched from the storage, though the value isn't decoded until it's scanned by the user.
When running a Select for example, the Record returned by the storage is just a `[]byte` alias called [`record.EncodedRecord`](https://godoc.org/github.com/asdine/genji/record#EncodedRecord).

Regarding key-only iteration and how it would be integrated in Genji, I think this can be a good optimisation for cases where only the primary key is used in the `WHERE` clause.

Examples:

```go
// fetch key only
db.Query("SELECT id FROM user WHERE id > 10")

// fetch key only because only the id is used in the where clause
db.Query("SELECT id, name FROM user WHERE id > 10")

// fetch both key and value
db.Query("SELECT id, name FROM user WHERE age > 18")
```

Then when iterating on the results:
- `SELECT id` -> only use the key
- `SELECT id, name` -> lazily fetch the value

**Comment by asdine** [comment]
Closing this as we are now [lazily reading](https://github.com/genjidb/genji/blob/adf452135d082b959f9235902eb44b17e255eb7e/database/table.go#L276-L282) the value from the store, it is only read if we need to access to one of the fields.
