### ISSUE TITLE
CLI doesn't display data of a database. 

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#418]
### What version of Genji are you using?

<pre>
$ genji version
Genji (devel)
Genji CLI (devel)
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?
Create a db file and insert some data into it. [sample code ](https://play.golang.org/p/kox_E3JSw9K) 
After that open the db with genji CLI and there is no data displayed.

Opening `my.db` with `boltbrowser` we can see all tables and its content.  

### What did you expect to see?

The `.tables.` command should display the list of tables;
`SELECT * FROM user;` should return the data the user table.

### What did you see instead?

`.tables` returns nothing
`SELECT * FROM user;` returns "user" not found.

### What Go version and environment are you using?

<pre>
$ go version
go version go1.16.3 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/touk/Library/Caches/go-build"
GOENV="/Users/touk/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/touk/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/touk/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/touk/workspace/dump/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ls/dpdwm5q966558yb487lfvn9r0000gn/T/go-build1173553683=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by asdine** [comment]
It's because you are using the main branch with an old compiled genji binary.
If you are using the main branch, you need to recompile the Genji binary every time you pull.

```sh
git clone git@github.com:genjidb/genji.git
cd genji/
make
```

**Comment by tzzed** [comment]
This is what I do. I did a new clone with a new compilation and it is the same behaviour.

**Comment by asdine** [comment]
I can't reproduce the error. Can you share your go.mod please?
What I suspect is one of these:
- the go.mod is pointing to the latest *release*, but the CLI is pointing to the latest *commit*
- the go.mod is pointing to the latest *commit*, but the CLI is pointing to the latest *release*
- you are reopening an old database

**Comment by tzzed** [comment]
Oh my bad,you're right the go.mod is pointing to the latest release, but the CLI is pointing to the latest commit. 
I close the issue.
