### ISSUE TITLE
StructScan panics when the interface parameter is not a struct

### ISSUE THREAD

**Issue by tzzed** [genjidb/genji#453]
### What version of Genji are you using?

<pre>
$ genji version
Genji (devel)
Genji CLI (devel)

</pre>

### What did you do?
StructScan panics when the api contract is not respected, it will be very good an error is returned instead of panic.

```go
        var b int
	d := document.NewFieldBuffer().Add("a", types.NewIntegerValue(10))
        err := document.StructScan(d, &b)
	assert.Error(t, err)
```

### What did you expect to see?
An error message.
```go
target must be pointer to struct
```

### What did you see instead?
```
panic: reflect: call of reflect.Value.NumField on int Value [recovered]
	panic: reflect: call of reflect.Value.NumField on int Value
```

**Comment by asdine** [comment]
Fixed by #487
