### ISSUE TITLE
The `=` conditional expression execution returns the result of the `LIKE` expression

### ISSUE THREAD

**Issue by startan** [genjidb/genji#458]
### What version of Genji are you using?

<pre>
$ genji version
Genji v0.14.1
Genji CLI v0.14.2
</pre>

### What did you do?
The following `TABLE` is created.
```sql
CREATE SEQUENCE IF NOT EXISTS seq_cizu;
CREATE TABLE IF NOT EXISTS cizu (
  id INTEGER NOT NULL DEFAULT (NEXT VALUE FOR seq_cizu),
  ci TEXT NOT NULL,
  explanation TEXT NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS IDX_CI ON cizu(ci);
```
The following SQL was executed
```sql
SELECT * from cizu where ci ='飞云';
```
### What did you expect to see?
Expect to return an empty result set because there are no eligible records.

### What did you see instead?
The `=` conditional expression execution returns the result of the `LIKE` expression

```shell
genji> SELECT * from cizu where ci ='飞云';
{
  "ci": "飞云丹",
  "explanation": "1.粉名。",
  "id": 62619
}
{
  "ci": "飞云履",
  "explanation": "1.相传为唐白居易居庐山草堂时自制鞋的名称。",
  "id": 62621
}
{
  "ci": "飞云掣电",
  "explanation": "1.形容非常迅速。",
  "id": 62618
}
{
  "ci": "飞云殿",
  "explanation": "1.指高耸入云的城楼。",
  "id": 62620
}
```

**Comment by asdine** [comment]
Thanks @startan! I can confirm that this issue no longer exists on the dev branch, the release will be published soon.
