### ISSUE TITLE
Add support for descending indexes

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#469]
```sql
CREATE INDEX on foo(a, b DESC, c ASC);
```

Notes:

- This will have an impact on the Compare function. It might need to be aware of the index information in order to order things correctly.

**Comment by zeina1i** [comment]
Hey @asdine I am working on this ticket.
one question: as Compare function is used internally by pebble and the parameters of it can not be changed, do you have any idea how could we make it happen to make the compare function aware of the index direction?

**Comment by asdine** [comment]
Hey @zeina1i, sorry this project was paused for a while and I just started working on it recently so I didn't notice your comment.
FWIW, the implementation can be found in the following commits 9af605ef9f4271c6d73e101d8e1a1789e599442c c6dd3cf33770904d9bb603830b3483759303dd01 f94c7034535e2d19b78d5a7f28bc98db24810b8d
