### ISSUE TITLE
Distributed Go app making use of your DB

### ISSUE THREAD

**Issue by idanasulinmemphis** [genjidb/genji#491]
This is actually a question.
First I tried to use your slack but I couldn't connect to your workspace for some reason.

I"m considering using your DB as an embedded DB in a distributed Go application. That means that in some way I should taking care of the DB instances to be synced.

1. Have you had the chance to hear about someone who did it?
2. Do you have any features to sync between different instances?
3. Does this project is ready for production?

Thanks

**Comment by asdine** [comment]
I don't recommend using Genji in a distributed setting unless you know exactly what you are doing.
Though it might be possible to do it, and it's certainly something that I would like to achieve at some point, no work has been done yet to make that happen.

1. No
2. No
3. No*. It's been used in production for a while but the database API is not stable yet so things can break in the future.

At this point, I would definitely recommend using something else if you need to sync data between services.

**Comment by idanasulinmemphis** [comment]
Ok thanks for the quick answer
