### ISSUE TITLE
UPDATE ... SET * = ... to change the complete document

### ISSUE THREAD

**Issue by Lercher** [genjidb/genji#495]
Version: `require github.com/genjidb/genji v0.15.1`

#### What is the current status of the proposed behavior? 

It's apparently easy and flexible to change a range of inner properties of an already existing document with update/set statements. However there appears to be no way to change the document as a whole. A workaround is to use a transaction to delete and then re-insert the new document. However, I did not evaluate if the internally used primary key changes. If so, I suppose, it would be a strange artifact of the workaround.

Another workaround is to wrap "the primary document" into a document with a single property, which can be set then. However, this seems to be complicating "create table" schemas and uses extra space in RAM during processing and on disk.

#### What is the proposed solution?

I propose to add the special path `*` which represents the root document. This enables syntax like `UPDATE tablename SET * = ? WHERE <some-predicate>` and looks as an idiomatic pair of the existing `SELECT * FROM tablename WHERE <some-predicate>` where `*` also means the whole document.

### Motivation

The motivation is to use the underlying Key Value store "as is" with familiar syntax. Especially in schema-less mode, all you know is the document itself and there is no intel on inner structure. So all you know is the PK and the document which needs to version keeping its identity (the PK). Think of a CMS storing arbitrary JSON content-documents during a redaction process.

Extending the semantics of path with `*` suggests limited implementation effort because most of the infrastructure in path traversal should be there already.

Thanks for considering,
Martin

**Comment by asdine** [comment]
It is already possible to replace a document entirely:

```sql
CREATE TABLE foo (
  a int primary key not null,
  b text
);

INSERT INTO foo (a, b) VALUES (1, 'version 1');

-- using standard SQL
INSERT INTO foo (a, b) VALUES (1, 'version 2') ON CONFLICT REPLACE;

-- using document notation
INSERT INTO foo VALUES {a: 1, b: 'version 3'} ON CONFLICT REPLACE;
```

In your code it would look like this:

```go
type Doc struct {
  A int
  B string
}

d := Doc{1, "Version 4"}
err = db.Exec("INSERT INTO foo VALUES ? ON CONFLICT REPLACE", &d)
```

You can see the documentation [here](https://genji.dev/docs/reference/insert/).

I will update it with a few examples.
