### ISSUE TITLE
Does genji support join feature?

### ISSUE THREAD

**Issue by Lvnszn** [genjidb/genji#496]
Hello everyone, I tried to write a few demos here, but found that it seems that genji does not support the join function.

version: genji v0.15.1

`db, err := genji.Open("mydb")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	db = db.WithContext(context.Background())

	err = db.Exec(`
        CREATE TABLE user_info (
            id              INT     PRIMARY KEY,
            phone            TEXT    NOT NULL UNIQUE,
        )
    `)
	db.Exec(`insert into user_info values (11, '18036086690')`)
	err = db.Exec(`
        CREATE TABLE user (
            id              INT     PRIMARY KEY,
            name            TEXT    NOT NULL UNIQUE,
            address (
                city        TEXT    DEFAULT "?",
                zipcode     TEXT
            ),
            friends         ARRAY
        )
    `)
	err = db.Exec(`
    INSERT INTO user (id, name, age, address, friends)
    VALUES (
        11,
        'Foo2',
        20,
        {"city": "Lyon", "zipcode": "69001"},
        ["foo", "bar", "baz"]
    )`)
	// Go structures can be passed directly
	type User struct {
		ID              uint
		Name            string
		TheAgeOfTheUser float64 `genji:"age"`
		Address         struct {
			City    string
			ZipCode string
		}
	}

	// Let's create a user
	u := User{
		ID:              20,
		Name:            "foo",
		TheAgeOfTheUser: 40,
	}
	u.Address.City = "Lyon"
	u.Address.ZipCode = "69001"

	err = db.Exec(`INSERT INTO user VALUES ?`, &u)
	// Query some documents
	res, err := db.Query("SELECT id, name, age, address FROM user WHERE age >= ?", 18)
	// always close the result when you're done with it
	defer res.Close()
	// Iterate over the results
	err = res.Iterate(func(d types.Document) error {
		// When querying an explicit list of fields, you can use the Scan function to scan them
		// in order. Note that the types don't have to match exactly the types stored in the table
		// as long as they are compatible.
		var id int
		var name string
		var age int32
		var address struct {
			City    string
			ZipCode string
		}

		err = document.Scan(d, &id, &name, &age, &address)
		if err != nil {
			return err
		}

		fmt.Println(id, name, age, address)

		// It is also possible to scan the results into a structure
		var u User
		err = document.StructScan(d, &u)
		if err != nil {
			return err
		}

		fmt.Println(u)

		// Or scan into a map
		var m map[string]interface{}
		err = document.MapScan(d, &m)
		if err != nil {
			return err
		}

		fmt.Println(m)
		return nil
	})
	
	res, err = db.Query("SELECT id, name, phone FROM user join user_info on user.id = user_info.id")
	if err != nil {
		panic(err)
	}

	res.Iterate(func(d types.Document) error {

		var id int
		var name string
		var phone string

		err = document.Scan(d, &id, &name, &phone)
		if err != nil {
			return err
		}

		fmt.Println(id, name, phone)
		return nil
	})`

**Comment by Lvnszn** [comment]
plz remove bug label...

**Comment by asdine** [comment]
No joins yet sorry
