### ISSUE TITLE
table.Info.DocidSequenceName sometimes gets wrong code when insert

### ISSUE THREAD

**Issue by hjlp20150803** [genjidb/genji#505]
### What version of Genji are you using?

```bash
github.com/genji/cmd/genji$ ./genji version
Genji (devel)
Genji CLI (devel)
github.com/genji/cmd/genji$ git log
commit c5d6f3b946694255389c11c1282d43489be43a8f (HEAD -> main, tag: v0.15.2, origin/main, origin/HEAD)
Author: Asdine El Hrychy [asdine.elhrychy@gmail.com](mailto:asdine.elhrychy@gmail.com)
Date: Sun Jun 18 11:38:12 2023 +0100

fix: deep copy strings during scan (#499)
```

### What did you do?

insert a table.I can't give you all the code, there are lots of table,lots of code.program goes good 2 times in 3, and the third time must goes wrong.

The table is:

```
genji> .schema req;
CREATE TABLE req (reqid BLOB NOT NULL, rpctype INTEGER, status INTEGER, lastreqid BLOB, reference TEXT DEFAULT "", sha TEXT DEFAULT "", lastsha TEXT DEFAULT "", signature TEXT DEFAULT "", time TEXT DEFAULT "", whom TEXT DEFAULT "", room TEXT NOT NULL, domain TEXT DEFAULT "");
genji>

2023/08/11 07:07:44 i req...sql(insert into req(reqid,rpctype,time,room,whom) values(?,?,?,?,?))err(1** "CTElDIE" not found)hex(e0cfd6c4fe878abdba05be2508000027)base(4M/WxP6Hir26Bb4lCAAAJw==)
```

'"CTElDIE" not found' always happened.

### What did you expect to see?
no error

### What did you see instead?
"CTElDIE" not found

### What I did?
I move the whole genji source code into project, change all the "github.com/genjidb/genji" to local, and repeat to dig,where goes wrong.

It take me several hours, I found the problem maybe here:
genji/internal/stream/table/insert.go

```go
// Iterate implements the Operator interface.
func (op *InsertOperator) Iterate(in *environment.Environment, f func(out *environment.Environment) error) error {
var newEnv environment.Environment
newEnv.Set(environment.TableKey, types.NewTextValue(op.Name))

var table *database.Table
return op.Prev.Iterate(in, func(out *environment.Environment) error {
	newEnv.SetOuter(out)

	d, ok := out.GetDocument()
	if !ok {
		return errors.New("missing document")
	}

	var err error
	if table == nil {
		table, err = out.GetCatalog().GetTable(out.GetTx(), op.Name)
		if err != nil {
			return err
		}
	}

	key, d, err := table.Insert(d)
	if err != nil {
		return err
	}

	newEnv.SetKey(key)
	newEnv.SetDocument(d)

	return f(&newEnv)
})
}
```

I found the problem is the table.Info.DocidSequenceName,it was wrong code, it should be "req_seq",not "CTElDIE", so I simplely add one code, and it works,but I don't konw where and how table.Info.DocidSequenceName gets wrong:

```go
func (op *InsertOperator) Iterate(in *environment.Environment, f func(out *environment.Environment) error) error {
var newEnv environment.Environment
newEnv.Set(environment.TableKey, types.NewTextValue(op.Name))

var table *database.Table
return op.Prev.Iterate(in, func(out *environment.Environment) error {
	newEnv.SetOuter(out)

	d, ok := out.GetDocument()
	if !ok {
		return errors.New("missing document")
	}

	var err error
	if table == nil {
		table, err = out.GetCatalog().GetTable(out.GetTx(), op.Name)
		if err != nil {
			return err
		}
	}
          //just let it be,and since it always be, why do we still need this one?
           table.Info.DocidSequenceName = table.Info.TableName + "_seq"
	key, d, err := table.Insert(d)
	if err != nil {
		return err
	}

	newEnv.SetKey(key)
	newEnv.SetDocument(d)

	return f(&newEnv)
})
}
```

I really hope your team can fixed it,by the way it's under windows10 platform, I haven't try other.And it's very curious, it always happens once in 3 times, and it must be the third time.DocidSequenceName value should change value randomly when it went wrong.
//genji/internal/database/catalog.go

```go
o, err := c.Cache.Get(RelationTableType, tableName)
```

c.tables in catalogCache gets wrong, it should combine sequences to create table.Info.DocidSequenceName, but I don't know how.

**Comment by hjlp20150803** [comment]
If you just open the app and close it, everything looks fine, but if you write something into db, and close app, the first and second time is ok , the third time went to wrong. I traced deep and deep, it looks like here:
genji/internal/database/catalogstore/store.go:

func loadCatalogStore(tx *database.Transaction, s *database.CatalogStore) (tables []database.TableInfo, indexes []database.IndexInfo, sequences []database.SequenceInfo, err error) {
	tb := s.Table(tx)

	err = tb.IterateOnRange(nil, false, func(key *tree.Key, d types.Document) error {
		tp, err := d.GetByField("type")
		if err != nil {
			return err
		}

		switch types.As[string](tp) {
		case database.RelationTableType:
			ti, err := tableInfoFromDocument(d)
			if err != nil {
				return errors.Wrap(err, "failed to decode table info")
			}
			tables = append(tables, *ti)
		case database.RelationIndexType:
			i, err := indexInfoFromDocument(d)
			if err != nil {
				return errors.Wrap(err, "failed to decode index info")
			}

			indexes = append(indexes, *i)
		case database.RelationSequenceType:
			i, err := sequenceInfoFromDocument(d)
			if err != nil {
				return errors.Wrap(err, "failed to decode sequence info")
			}
			sequences = append(sequences, *i)
		}

		return nil
	})
	return
}

I check the ti ,add a fmt.Println("geinji.loadCatalogStore:", ti.DocidSequenceName, ti.TableName), ti.DocidSequenceName, ti.TableName are all ok.
			ti, err := tableInfoFromDocument(d)
			if err != nil {
				return errors.Wrap(err, "failed to decode table info")
			}
                        fmt.Println("geinji.loadCatalogStore:", ti.DocidSequenceName, ti.TableName)
			tables = append(tables, *ti)
but after the IterateOnRange call, I check the tables,TableName is still good, and DocidSequenceName missed.

**Comment by hjlp20150803** [comment]
func loadCatalogStore(tx *database.Transaction, s *database.CatalogStore) (tables []database.TableInfo, indexes []database.IndexInfo, sequences []database.SequenceInfo, err error) 
tables data have been broken after tb.IterateOnRange call, I am not familiar to the system, so I can't find out why.

It happened when there are something have been written into db, and break program(this maybe cause genjidb have no chance to finish something.

**Comment by asdine** [comment]
@hjlp20150803 Please let me decide if I should close the issue or not.
This is a *free*, open source project, so bugs fixes like this take time.
If you need the fix quickly, I'm happy to take a PR, otherwise I'll deal with this whenever I can.

**Comment by hjlp20150803** [comment]
> @hjlp20150803 Please let me decide if I should close the issue or not. This is a _free_, open source project, so bugs fixes like this take time. If you need the fix quickly, I'm happy to take a PR, otherwise I'll deal with this whenever I can.

ok, I fixed in easy way:
/genji/internal/database/catalogstore/store.go
func tableInfoFromDocument(d types.Document) (*database.TableInfo, error) {
 ....
	v, err = d.GetByField("docid_sequence_name")
	if err != nil && !errors.Is(err, types.ErrFieldNotFound) {
		return nil, err
	}
	if err == nil && v.Type() != types.NullValue {
		ti.DocidSequenceName = types.As[string](v)
	}

	return &ti, nil
}
ti.DocidSequenceName = types.As[string](v) cause the ti.DocidSequenceName pointer to wrong place, always cause "unexpected fault address 0x29e74135d4a
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0x29e74135d4a pc=0x14c2b9a]"
Entry database by genji, 
select * from __genji_catalog
everything is fine, such as:
{
  "name": "req",
  "type": "table",
  "namespace": 82,
  "sql": "CREATE TABLE req (reqid BLOB NOT NULL, rpctype INTEGER, status INTEGER, lastreqid BLOB, reference TEXT DEFAULT \"\", sha TEXT DEFAULT \"\", lastsha TEXT DEFAULT \"\", signature TEXT DEFAULT \"\", time TEXT DEFAULT \"\", whom TEXT DEFAULT \"\", room TEXT NOT NULL, domain TEXT DEFAULT \"\")",
  "docid_sequence_name": "req_seq"
}
{
  "name": "req_seq",
  "type": "sequence",
  "sql": "CREATE SEQUENCE req_seq CACHE 64",
  "owner": {
    "table_name": "req"
  }
}

so I figure the bug could be
stmt, err := parser.NewParser(strings.NewReader(types.As[string](s))).ParseStatement()
or 
v, err = d.GetByField("docid_sequence_name")

so I just replace 
ti.DocidSequenceName = ti.TableName + "_seq"
it works.

**Comment by hjlp20150803** [comment]
"fmt.Println(ti.DocidSequenceName)" would crashed the program.

**Comment by asdine** [comment]
The bug is probably related to https://github.com/genjidb/genji/issues/508, which has been fixed.
Please reopen if the bug still occurs
