### ISSUE TITLE
The table is deleted, why is the space not freed

### ISSUE THREAD

**Issue by sj1385** [genjidb/genji#506]
I have a test table with a capacity of 2GB，After execute a drop table operation, the capacity of the disk does not decrease。
The table is deleted, why is the space not freed

**Comment by asdine** [comment]
Genji doesn't control how the disk is used, Pebble does.
Pebble provides a default cleaner that eventually cleans up deleted files. If you want to customize it, see the [Options](https://pkg.go.dev/github.com/cockroachdb/pebble?utm_source=godoc#Options) type
