### ISSUE TITLE
Support for FillPercent/bbolt

### ISSUE THREAD

**Issue by jscoys** [genjidb/genji#58]
Hello

I’m trying to find a way to specify the FillPercent value on the bbolt Engine without success.

The default value is 0.5, would like to put a 0.9. Do you know how to proceed through Genji when creating the db/bucket?

Thx

**Comment by jscoys** [comment]
@asdine can you help me please? Thx

**Comment by asdine** [comment]
There is currently no way to customize the way the Bolt engine is running, besides the bolt options.

```go
db, err := genji.New(boltengine.New("my.db", 0600, &bolt.Options{...}))
```

`FillPercent` must be set up manually on the required bucket on every transaction, which is not possible at this moment. Also, it would also mean that it should be table-specific, which is even more complicated. 

Perhaps it would be interesting to be able to customize the engine further, with something like this:

```go
db, err := genji.New(boltengine.New("my.db", &boltengine.Options{
  FillPercent: 0.9,
  Mode: 0600,
  Options: &bolt.Options{},
}))
```

but it means having a FillPercent value that would be the same for all buckets.

Could you describe why you need to have access to the FillPercent feature?

**Comment by jscoys** [comment]
Well first thx for your answer!

It’s the first time I’m using bbolt and I’m adding a basic struct with 10 fields (mix of string/date/int) in a loop adding a total of 12,000 records and I end up with a DB size of 1 gigs. It seems to me that it’s big for the data I’m putting there...

I red on some forums that of the db is reaching a size it’s doubling the size with « blank spaces ». It’s allowing the dB to grow faster (scale better), but for the space it’s not optimal at all... and it seems this theory is good because I see the dB size growing like 32, then 64, 128, 256, 512 and then jumping directly to 1024 mbytes. On these forums people are saying that we can change the FillPercent per bucket, and putting a 0.9 value would solve the issue. That’s why I’m asking.

Hum won’t be proud of it but can I change something directly in the code of the package locally to make it possible? Like a hack I would say?

**Comment by jscoys** [comment]
Oh just red again your second option it’s not an issue to have the same FillPercent for all buckets! So I can create the dB with a Genji.New()? I will give it a try as soon as I can.

**Comment by asdine** [comment]
Closing this as Bolt is no longer supported
