### ISSUE TITLE
Support dot notation on UPDATE ... SET

### ISSUE THREAD

**Issue by asdine** [genjidb/genji#84]
Currently, the `UPDATE` clause only accepts simple top-level fields `foo`.
We should be able to update nested fields or array indexes using [dot notation](https://genji.dev/docs/genji-sql/lexical-structure/#dot-notation).

```sql
UPDATE users SET a.3.name = [1, 2, 3];
```

Because nested values can be tricky, the SET clause must only set a value when it is possible. If we take the example above, the document must respect the following requirements in order to be settable:

- `a` is an array
- `a.3` exists and is a document
- `a.3.name` may or may not exist (same rules as for top-level fields, see below)

Currently, the rule is: _if the field doesn't exist, we create it, otherwise we replace it with the new value_.
With this change, the rule still applies but only for the element of the dot notation path that is the most to the right.

### Exception for arrays

```sql
INSERT INTO users (a) VALUES ([1, 0, 0]), ([2, 0]);
UPDATE users SET a.2 = 1;
SELECT * FROM users WHERE a.2 = 1;
{"a": [1, 0, 1]}
```

This example shows that the above rule must not apply for arrays. If the array index doesn't exist, it must not be created.

**Comment by tzzed** [comment]
If the field `name` doesn't exist, it must be created. Consider the following request:
`UPDATE users SET a.2.name = [1, 2, 3];
SELECT * FROM users WHERE a.2= "name";`

Is the expected result?
`{
  "a": [
    1,
    0,
    "name",
    [
      1,
      0,
      3
    ]
  ]
}`

**Comment by asdine** [comment]
I'm reopening this issue as there are still some bugs in the proposed PR. The PR has been reverted and the issue is scheduled for v0.8

**Comment by tzzed** [comment]
When the field using backquotes with spaces like this some "field ", the spaces must be deleted or not?
input:

` some "field" ` or `a.     b   . c` 
outputs :

 `some "field" `  or  `a.b.c`
Spaces should be deleted.
Is the expected behaviour?

**Comment by tzzed** [comment]
Found the answer in `TestParserPath`.
