### ISSUE TITLE
Inserting empty array and document into boolean field

### ISSUE THREAD

**Issue by yaziine** [genjidb/genji#89]
If I insert an empty array or an empty document into a boolean field, I would expect that the value of that field will be `false`. Exactly the same way as with empty strings.

What do you think?

```sql
genji> CREATE TABLE test(a bool, b bool, c bool);
genji> INSERT INTO test VALUES {a: "", b: [], c: {}};
genji> SELECT * FROM test;
{
  "a": false,
  "b": true,
  "c": true
}
```

**Comment by asdine** [comment]
Probably an error in their zero value in the document package

**Comment by yaziine** [comment]
I've added this for the current milestone.
