### ISSUE TITLE
Update a document where the field is a stringified integer

### ISSUE THREAD

**Issue by yaziine** [genjidb/genji#93]
The documentation says:
> A document is an object that contains pairs that associate a string field to a value of any type.

[source](https://genji.dev/docs/genji-sql/documents/)

Given this, I may do:
```
genji> create table foo;
genji> insert into foo values {"1": "one"};
genji> select * from foo;
{
  "1": "one"
}
```

But if I want to update the `"1"` field, I get an error:
```
genji> update foo set "1" = "un";
found 1, expected identifier at line 1, char 15
genji> update foo set 1 = "un";
found 1, expected identifier at line 1, char 16
```

**Comment by asdine** [comment]
Actually it's not an error, you just need to write the query differently:

```sql
update foo set `1` = "un";
```

After `SET`, the parser expects an identifier, which can be written in two ways.
You can take a look at this documentation to learn more about that: https://genji.dev/docs/genji-sql/lexical-structure/#identifiers

**Comment by yaziine** [comment]
Indeed, closing the issue.
